=encoding utf8

=head1 NAME

Git::Crypt - Encrypt/decrypt sensitive files saved on public repos

=head1 SYNOPSIS

#Usage#1: Provide the cipher instance

  my $gitcrypt = Git::Crypt->new(
      files => [
          {
              file => 'file1',
              is_encrypted => 0,
          },
          {
              file => 'file2',
              is_encrypted => 0,
          },
      ],
      cipher => Crypt::CBC->new(
          -key      => 'a very very very veeeeery very long key',
          -cipher   => 'Blowfish',
          -salt     => pack("H16", "very very very very loooong salt")
      )
  );

  #gitcrypt->add([qw| file1 file2 |]);
  #gitcrypt->del([qw| file1 file2 |]);
  #gitcrypt->key('some key');
  #gitcrypt->salt('some key');
  $gitcrypt->crypt;     #save files encrypted
  $gitcrypt->decrypt;   #save files decrypted

#Usage#2: Provide key, salt and cipher name

  my $gitcrypt = Git::Crypt->new(
      files => [
          {
              file => 'file1',
              is_encrypted => 0,
          },
          {
              file => 'file2',
              is_encrypted => 0,
          },
      ],
      key         => 'a very very very veeeeery very long key',
      cipher_name => 'Blowfish',
      salt        => pack("H16", "very very very very loooong salt")
  );

  #gitcrypt->add([qw| file1 file2 |]);
  #gitcrypt->del([qw| file1 file2 |]);
  #gitcrypt->key('some key');
  #gitcrypt->salt('some key');
  $gitcrypt->crypt;     #save files encrypted
  $gitcrypt->decrypt;   #save files decrypted

#Usage#3: Command line tool:
    
    #initialize gitcrypt and its config
    gitcrypt init
    
    #set a gitcrypt cipher
    gitcrypt set cipher Blowfish

    #set a key
    gitcrypt set key    some key

    #set a salt
    gitcrypt set salt   some key

    #list files
    gitcrypt list

    #add files in gitcrypt
    gitcrypt add file1-tests file2-tests

    #del files in gitcrypt
    gitcrypt del file1-tests file2-tests

    #encrypt files that are not encrypted yet
    gitcrypt encrypt

    #decrypt files that are encrypted
    gitcrypt decrypt

=head1 DESCRIPTION

Git::Crypt can be used to encrypt files before a git commit. That way its possible to upload encrypted files to public repositories.
Git::Crypt encrypts line by line to prevent too many unnecessary diffs between encrypted commits.

=head1 AUTHOR

    Hernan Lopes
    CPAN ID: HERNAN
    perldelux
    hernanlopes@gmail.com
    http://www.perldelux.com

=head1 COPYRIGHT

This program is free software; you can redistribute
it and/or modify it under the same terms as Perl itself.

The full text of the license can be found in the
LICENSE file included with this module.


=head1 SEE ALSO

perl(1).

=cut

1;
